apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-api
    newName: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-api
    newTag: "9680ee5c30c07f00be8942a8f059c358f814c274"

  - name: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-worker
    newName: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-worker
    newTag: "9680ee5c30c07f00be8942a8f059c358f814c274"

labels:
  - pairs:
      environment: dev