apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-api
    newName: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-api
    newTag: "f31c7b71d203655434148b3c7cd17d6f75ea928b"

  - name: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-worker
    newName: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-worker
    newTag: "f31c7b71d203655434148b3c7cd17d6f75ea928b"

labels:
  - pairs:
      environment: dev