apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: image-processing
  namespace: argocd
spec:
  description: Image Processing Platform

  sourceRepos:
    - https://github.com/Pioti2252/GCP-Image-Processing-Pub-Sub.git

  destinations:
    - namespace: image-processing
      server: https://kubernetes.default.svc

    - namespace: image-processing-prod
      server: https://kubernetes.default.svc

    - namespace: kyverno
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

    - group: kyverno.io
      kind: ClusterPolicy

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"