apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - disallow-latest-tag.yaml
  - require-non-root.yaml
  - require-resources.yaml
  - allowed-image-registries.yaml
  - require-restricted-security-context.yaml