apiVersion: v1
kind: ConfigMap
metadata:
  name: image-processing-config
  namespace: image-processing
data:
  DB_URL: jdbc:postgresql://127.0.0.1:5432/image_processing
  DB_USERNAME: image_app

  PUBSUB_PROJECT_ID: gcp-image-pub-sub
  PUBSUB_TOPIC_ID: image-jobs-dev
  PUBSUB_SUBSCRIPTION_ID: image-jobs-worker-dev

  STORAGE_BUCKET_NAME: gcp-image-pub-sub-image-processing-dev
  STORAGE_UPLOAD_PREFIX: uploads/
  STORAGE_PROCESSED_PREFIX: processed/

  LOCAL_DEAD_LETTER_HANDLING: "false"
  WORKER_MAX_ATTEMPTS: "5"