apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-processing-db
  namespace: image-processing
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore

  target:
    name: image-processing-db
    creationPolicy: Owner

  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: image-processing-dev-database-password
        version: latest