apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: image-api
  namespace: image-processing
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: image-api

  namespaceSelector:
    matchNames:
      - image-processing

  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s