apiVersion: v1
kind: Service
metadata:
  name: image-worker
  namespace: image-processing
  labels:
    app: image-worker
spec:
  type: ClusterIP
  selector:
    app: image-worker
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP