apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-api
  namespace: image-processing
  annotations:
    iam.gke.io/gcp-service-account: image-api-dev@gcp-image-pub-sub.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-worker
  namespace: image-processing
  annotations:
    iam.gke.io/gcp-service-account: image-worker-dev@gcp-image-pub-sub.iam.gserviceaccount.com