apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: image-processing-prod

resources:
  - ../../base

images:
  - name: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-api
    newName: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-api
    digest: "sha256:4d11519be9a3996c2c718d54d8a99d76b83388eb308be918b29796ffc48945c0"

  - name: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-worker
    newName: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-worker
    digest: "sha256:907eceefcb6a2c91aef43be9716bd6637c74c2335e5b2f860cf5b18150bb4c36"

labels:
  - pairs:
      environment: prod

patches:

  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: image-api
    patch: |-
      - op: replace
        path: /spec/namespaceSelector/matchNames/0
        value: image-processing-prod

  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: image-worker
    patch: |-
      - op: replace
        path: /spec/namespaceSelector/matchNames/0
        value: image-processing-prod

  # ============================================================
  # PROD ConfigMap
  # ============================================================
  - target:
      version: v1
      kind: ConfigMap
      name: image-processing-config
    patch: |-
      - op: replace
        path: /data/PUBSUB_TOPIC_ID
        value: image-jobs-prod

      - op: replace
        path: /data/PUBSUB_SUBSCRIPTION_ID
        value: image-jobs-worker-prod

      - op: replace
        path: /data/STORAGE_BUCKET_NAME
        value: gcp-image-pub-sub-image-processing-prod

  # ============================================================
  # image-api Workload Identity
  # ============================================================
  - target:
      version: v1
      kind: ServiceAccount
      name: image-api
    patch: |-
      - op: replace
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: image-api-prod@gcp-image-pub-sub.iam.gserviceaccount.com

  # ============================================================
  # image-worker Workload Identity
  # ============================================================
  - target:
      version: v1
      kind: ServiceAccount
      name: image-worker
    patch: |-
      - op: replace
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: image-worker-prod@gcp-image-pub-sub.iam.gserviceaccount.com

  # ============================================================
  # image-api -> Cloud SQL PROD
  # cloud-sql-proxy jest drugim kontenerem w Podzie
  # ============================================================
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: image-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/1/args/3
        value: gcp-image-pub-sub:europe-central2:image-processing-prod-postgres

  # ============================================================
  # image-worker -> Cloud SQL PROD
  # ============================================================
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: image-worker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/1/args/3
        value: gcp-image-pub-sub:europe-central2:image-processing-prod-postgres

  # ============================================================
  # ExternalSecret -> Secret Manager PROD
  # ============================================================
  - target:
      group: external-secrets.io
      version: v1
      kind: ExternalSecret
      name: image-processing-db
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: image-processing-prod-database-password
