apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: image-processing-prod

resources:
  - ../../base

images:
  - name: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-api
    newName: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-api
    newTag: "cc9bab26638251463064c832e10184f2147f80a4"

  - name: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-worker
    newName: europe-central2-docker.pkg.dev/gcp-image-pub-sub/image-processing-dev/image-worker
    newTag: "cc9bab26638251463064c832e10184f2147f80a4"

labels:
  - pairs:
      environment: prod